// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kldjajwwyluhvkcubrlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZGphand3eWx1aHZrY3VicmxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMDAxNzYsImV4cCI6MjA3OTU3NjE3Nn0.ROuNGBAeVBZ9Cw40phv5rm7z08D0fJOTiClN216eoEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});